"""Measurement and testimonial reliability certificates.

These are deliberately narrow executable benchmark models.

Measurement:
- records a measured value together with a non-negative standard uncertainty;
- requires explicit traceability/calibration metadata;
- warrants recording the measurement result, not accepting a proposition.

Testimony:
- models a binary report channel with sensitivity and false-positive rate;
- combines that channel with an explicit prior via Bayes' rule;
- warrants recording the posterior generated by that declared model, not
  accepting the reported proposition or treating source reliability as globally
  context-free.

Neither model is intended as a universal theory of measurement or testimony.
"""
from __future__ import annotations

from dataclasses import dataclass
from math import isfinite


def _probability(value: float, field: str) -> float:
    if not isfinite(value) or value < 0.0 or value > 1.0:
        raise ValueError(f"{field} must be a finite probability in [0, 1]")
    return value


@dataclass(frozen=True)
class MeasurementCertificate:
    """One measurement result with explicit uncertainty and traceability."""

    id: str
    quantity: str
    value: float
    standard_uncertainty: float
    unit: str
    calibration_ref: str
    measurement_model_ref: str | None = None

    def __post_init__(self) -> None:
        if not self.id:
            raise ValueError("measurement certificate id must be non-empty")
        if not self.quantity:
            raise ValueError("measurement quantity must be non-empty")
        if not self.unit:
            raise ValueError("measurement unit must be non-empty")
        if not self.calibration_ref:
            raise ValueError("calibration reference must be non-empty")
        if not isfinite(self.value):
            raise ValueError("measurement value must be finite")
        if (
            not isfinite(self.standard_uncertainty)
            or self.standard_uncertainty < 0.0
        ):
            raise ValueError(
                "standard uncertainty must be finite and non-negative"
            )


@dataclass(frozen=True)
class TestimonyReliabilityModel:
    """Binary source/report channel relative to an explicit reference class.

    sensitivity = P(report-positive | claim-true)
    false_positive_rate = P(report-positive | claim-false)
    """

    source_id: str
    reference_class: str
    sensitivity: float
    false_positive_rate: float

    def __post_init__(self) -> None:
        if not self.source_id:
            raise ValueError("source id must be non-empty")
        if not self.reference_class:
            raise ValueError("reference class must be non-empty")
        object.__setattr__(
            self,
            "sensitivity",
            _probability(self.sensitivity, "sensitivity"),
        )
        object.__setattr__(
            self,
            "false_positive_rate",
            _probability(
                self.false_positive_rate,
                "false_positive_rate",
            ),
        )


@dataclass(frozen=True)
class TestimonyCertificate:
    """One positive testimonial report under one declared reliability model."""

    id: str
    claim: str
    prior_probability: float
    reliability: TestimonyReliabilityModel

    def __post_init__(self) -> None:
        if not self.id:
            raise ValueError("testimony certificate id must be non-empty")
        if not self.claim:
            raise ValueError("testimony claim must be non-empty")
        object.__setattr__(
            self,
            "prior_probability",
            _probability(self.prior_probability, "prior_probability"),
        )

    @property
    def report_probability(self) -> float:
        prior = self.prior_probability
        model = self.reliability
        return (
            model.sensitivity * prior
            + model.false_positive_rate * (1.0 - prior)
        )

    @property
    def posterior_probability(self) -> float:
        denominator = self.report_probability
        if denominator == 0.0:
            raise ValueError(
                "positive report has zero probability under the declared model"
            )
        return (
            self.reliability.sensitivity * self.prior_probability
        ) / denominator
